### ISSUE TITLE
How do I pause the timer?

### ISSUE THREAD

**Issue by nozavroni** [harshen/jQuery-countdownTimer#10]
In the documentation I see an option to provide an id for a pause button, but I need to know how to simply pause the timer without a button. Can't I just call some method like Countdowntimer.pause() or something?

**Comment by harshen** [comment]
Hi,

With the new version 2.0.0, providing **pause** function which can be used to pause and resume the timer.

More information:- [jQuery-countdownTimer](https://harshen.github.io/jQuery-countdownTimer/)
