### ISSUE TITLE
action hooks?

### ISSUE THREAD

**Issue by chrisdrappier** [harshen/jQuery-countdownTimer#11]
Is it possible to associate any actions with the countdown timer? I'm using it to remind users when their session is about to expire, and when it gets close to the end I want to use an alert popup to remind them to save before their session expires.

**Comment by harshen** [comment]
Use **beforeExpiryTime** and **beforeExpiryTimeFunction** options.

More information:- [jQuery-countdownTimer](https://harshen.github.io/jQuery-countdownTimer/)
