### ISSUE TITLE
timeUp Callback is running even no time up

### ISSUE THREAD

**Issue by vijaykc** [harshen/jQuery-countdownTimer#12]
timeUp Callback is running even no time up for following browser.

Can you give me any suggestation to fix the issue?
iPhone 6s Plus
Nexus 6 Android Chrome
iPhone 6 Plus
WinPhone 8.1

Is there any script added to run this function for above browsers?

**Comment by jigneshthummar** [comment]
issue in firefox as well

**Comment by harshen** [comment]
With the new version 2.0.0, **timeUp** callback is working with all the mentioned browsers.

**Comment by harshen** [comment]
With the new version 2.0.0, **timeUp** callback is working with all the mentioned browsers.
