### ISSUE TITLE
Hi how to remove the seconds from timer ??? I have already gone through your documentation please revert

### ISSUE THREAD

**Issue by prashantkudale** [harshen/jQuery-countdownTimer#13]
I have used the function which will take only two arguments as hours and minutes but still it displaying the seconds please help us to resolve this issue.

**Comment by dzeroone** [comment]
Try something like this
```
$(function(){
	$("#future_date").countdowntimer({
                dateAndTime : "2018/01/01 00:00:00"‚
		size : "lg"‚
		regexpMatchFormat: "([0-9]{1,2}):([0-9]{1,2}):([0-9]{1,2}):([0-9]{1,2})"‚
      		regexpReplaceWith: "$2<sup>hours</sup> / $3<sup>minutes</sup>"
	});
});
```

**Comment by harshen** [comment]
Hi,

With the new version 2.0.0, providing ```displayFormat``` option which can be used to show only necessary time periods.

```
displayFormat : "YODHMS"
```

More information:- [jQuery-countdownTimer](https://harshen.github.io/jQuery-countdownTimer/)
