### ISSUE TITLE
How to fire a event before 5 mins of expiry?

### ISSUE THREAD

**Issue by praveenlobo7** [harshen/jquery-countdownTimer#15]
How to fire a event before 5 mins of expiry

**Comment by praveenlobo7** [comment]
Any updates?

**Comment by csaritha19** [comment]
Any updates? I am having the same issue.

**Comment by tgg-pawan** [comment]
how to set time zone

**Comment by harshen** [comment]
With the new version, providing options beforeExpiryTime and beforeExpiryTimeFunction to provide with functionality of executing instructions at a time before expiry time. 

Time zones can be set on server side. Nothing can be done on client side and hence with countdowntimer with respect to it.
