### ISSUE TITLE
Two different timers on the same page

### ISSUE THREAD

**Issue by maustyle** [harshen/jquery-countdownTimer#16]
Is it possible to have two different countdown timers on the same page?

for example:

```
$('.future_date_1').countdowntimer({dateAndTime : "2016/02/20 9:40:00",size : "lg"});
$('.future_date_2').countdowntimer({dateAndTime : "2016/02/20 10:00:00",size : "lg"});
```

**Comment by devpilot** [comment]
Looks like currently it's not possible with same Settings

**Comment by harshen** [comment]
Hi,

Try it with element id. It definitely works.

$('#future_date_1').countdowntimer({dateAndTime : "2018/02/20 9:40:00",size : "lg"});
$('#future_date_2').countdowntimer({dateAndTime : "2018/02/20 10:00:00",size : "lg"});
