### ISSUE TITLE
Time Countdown when refresh page

### ISSUE THREAD

**Issue by romanreign** [harshen/jquery-countdownTimer#17]
Hello,
I am using jquery-countdownTimer, it's good! When I refresh my page, I have a problem: it does not continue to count down the time which is counting down before. So can you give me a solution for that? Thanks in advance.

**Comment by harshen** [comment]
Hi,
It depends on the type of timer you are using. If you set the timer to a future date then it does not continue to count down the time which its counting down before on page refresh. 

for eg:-

$("#future_date").countdowntimer({
                dateAndTime : "2018/01/01 00:00:00"‚
		size : "lg"
	});

Here, the countdown timer will countdown reverse to "2018/01/01 00:00:00" from current time.

For other cases in which you supply the hours, minutes, seconds for reverse countdown, the timer will continue to count down the time which its counting down before on page refresh.

for eg:-

$(function(){
	$("#hms_timer").countdowntimer({
                hours : 3‚
		minutes : 10‚
                seconds : 10‚
                size : "lg"
	});
});

Here, on page refresh everytime the timer is reset to 03:10:10. Hope this helps.
Try the demo for more clarity:-
http://harshen.github.io/jquery-countdownTimer/
