### ISSUE TITLE
Last call override previous call's options

### ISSUE THREAD

**Issue by devpilot** [harshen/jquery-countdownTimer#18]
Lets say my page have to show multiple timers with different `{startDate : x, dateAndTime : x}` .

Last call to countdowntimer() overriding all previous timers. :sweat:

`$(".timer_x").countdowntimer({
     startDate : x,
      dateAndTime : x
});`

If the _options_ are different for different calls then timers are working as you showed on your demo.

**Comment by harshen** [comment]
Hi,
Use element id instead of class. It definitely works.

$("#timer_x").countdowntimer({ startDate : x, dateAndTime : x });
