### ISSUE TITLE
Running timer daily till 3 pm without setting manually

### ISSUE THREAD

**Issue by MakkPresstech** [harshen/jquery-countdownTimer#19]
Here is how we did it:

This is a timer till 3 PM everyday.

<script>
  
  
    var pepe=0;
   function minutesUntilMidnight() {
    var midnight = new Date();
    midnight.setHours( 24 );
    midnight.setMinutes( 0 );
    midnight.setSeconds( 0 );
    midnight.setMilliseconds( 0 );
    return ( midnight.getTime() - new Date().getTime() ) / 1000 / 60;
}
  
  var meme= minutesUntilMidnight();
  
  var chumk= meme/60;
  if(chumk >= 9){
    
    pepe= chumk-9;
    
  }else{
  pepe= chumk+15;
  }
  
  
  
// Set the date we're counting down to
var countDownDate = new Date(new Date().getTime() + pepe  60  60 * 1000);

// Update the count down every 1 second
var x = setInterval(function() {

    // Get todays date and time
    var now = new Date().getTime();
    
    // Find the distance between now an the count down date
    var distance = countDownDate - now;
    
    // Time calculations for days, hours, minutes and seconds
     var days = Math.floor(distance / (1000  60  60 * 24));
    var hours = Math.floor((distance % (1000  60  60  24)) / (1000  60 * 60));
    var minutes = Math.floor((distance % (1000  60  60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
    // Output the result in an element with id="demo"
    document.getElementById("demo").innerHTML =  hours + " Hours "
    + minutes + " Mins " + seconds + " Secs ";
    
    // If the count down is over, write some text 
    if (distance < 0) {
        clearInterval(x);
        document.getElementById("demo").innerHTML = "00 00 00";
    }
}, 1000);
</script>

**Comment by harshen** [comment]
What are you trying to achieve. Is there any issue with countdowntimer ?

**Comment by harshen** [comment]
It doesn't seem to be an issue with countdowntimer, hence closing the issue.
