### ISSUE TITLE
Multiple countdowntimers on same page

### ISSUE THREAD

**Issue by godwingomez** [harshen/jquery-countdownTimer#2]
Suppose if we have multiple countdown timers (of different dates) in a page and If call a generalized function(calls the coutdowntimer plugin) to display the countdown timer by passing the parameters 'dateTime' & 'selector', then all the timer in the page will show the same timer. 

I feel that the 'window.dateTime' variable in the function 'givenDate' is causing the issue. This variable name should be dynamic in nature, which should be based on the selector also.

**Comment by DhanrajMC** [comment]
Hi harshen,
Thanks for the timer code . There are multiple products in a page i need to display timer for each. i made a "for each" (via jquery), and called your countdowntimer function , 

My final result is ,it picks the  last products time and populates that time to rest of the products present in the page and it is running very fast as well (like seconds decrementing by 3 ,4 seconds) could you please us?
