### ISSUE TITLE
Stop Timer without changing its control name Stop to Start

### ISSUE THREAD

**Issue by PradeepYadav123** [harshen/jquery-countdownTimer#20]
Hi,

I just want to stop timer on stop button click without changing control text.
Its working fine but i don't need to change the text of button.
How can i implement this.
Request you to please do the needful to help me.

Thanks in advanced!

**Comment by harshen** [comment]
Hi,

Replace line 791 :-
$("#" + opts.stopButton).val("start").text("Start");

With the below code:-

$("#" + opts.stopButton).val("start");
