### ISSUE TITLE
beforeExpiryTime is not working

### ISSUE THREAD

**Issue by sudeepvarma1498** [harshen/jquery-countdownTimer#24]
$("#timer").countdowntimer({
		    hours : 00,
		    minutes : 00,
		    seconds : 10,
		    size : "lg",
		    beforeExpiryTime :null‚
		    beforeExpiryTimeFunction :  alertt
	 	});

its showing error unexpexted token at Line beforeExpiryTime

**Comment by harshen** [comment]
Hi,

It doesn't seem to be an issue with the timer. For support please write me to harshenpandey@gmail.com.

Meanwhile You can also refer the documentation.
