### ISSUE TITLE
Reset Timer using a function instead of button

### ISSUE THREAD

**Issue by clveranis** [harshen/jQuery-countdownTimer#25]
Hi there, 

Let me start out by saying that this plugin is exactly what I needed and great work on it! However, I've been trying to figure out how to manually reset the timer via function in another js file (using this plugin within a Ruby On Rails app, so there are multiple JS files for various needs).

I've attempted to write a new function within jquery.countTimer.js using some of the code inside of your Start/Stop Timer function for using a button click but ultimately it feels like a hack and I haven't been able to get it to work correctly. 

Could you please kindly write or instruct me on how to add a function to be able to reset an **existing** timer via a straight call? Something along the lines of `$('#timerDiv').countdowntimer().reset();` would be perfect.

Thanks!
-Charles

P.S. - The usage of this would be within an ajax call, so each time the ajax call is made, the timer needs to be reset, if that helps provide some more background info. Thanks!

**Comment by harshen** [comment]
Hi,
With the new version 2.0.0,  providing stop function which can be used to stop and restart the timer.

Usage:-
jQuery("#hms_timer").countdowntimer("stop", "stop");
jQuery("#hms_timer").countdowntimer("stop", "start");

When stopped, the timer resets itself to the defined values.

More information:- https://harshen.github.io/jQuery-countdownTimer/

**Comment by clveranis** [comment]
@harshen thank you very much! This is exactly what I was looking for! Great update 👍
