### ISSUE TITLE
Timer seconds multiplies with every click

### ISSUE THREAD

**Issue by SandeshSarfare** [harshen/jQuery-countdownTimer#28]
In my scenario , on click ajax request is made which again initializes countdowntimer() with coundown time but with every click, the timer speed multiplies. In one second tick those many seconds are elapsed.

**Comment by harshen** [comment]
In your case, the timer is reinitialising everytime the ajax call is made without the previous instance reaching time expire i.e. zero. You are trying to call the plugin method multiple times on same element before previous instance reaches zero which creates a loop. This seems not to be an issue with timer. Try different approach.

**Comment by SandeshSarfare** [comment]
Initializing timer only once on document.ready() helped. Thanks a lot.

**Comment by clveranis** [comment]
@SandeshSarfare [My question](https://github.com/harshen/jquery-countdownTimer/issues/25) is related to the exact same issue. What I have done is, on each ajax call remove the element where the timer is being displayed from the dom entirely, then recreate that same element and reinitialize the timer with the same parameters originally.

Its a bit crude but it works. Hopefully we will have a way to reset the timers eventually.

Hope this helps.

**Comment by aranderia** [comment]
@clveranis I tried doing the same thing as you suggested. 

Removing the element, adding it back and reinitialize the timer, still it does not work and the second multiples with every click.

Please see this code below.

var myEl = angular.element(document.querySelector('#hm_timer_'+t_id)); // t_id -> I save the id in this variable from the loop
myEl.remove();

var newmyEl = angular.element(document.querySelector('#timer_'+t_id));  // this is the parent div
var newDiv = "<span id='hm_timer_"+t_id+"'></span>"; (Created a span with the same id)
newmyEl.append(newDiv);

$('#hm_timer_'+t_id).countdowntimer({
hours : hours,
minutes : minutes,
seconds : seconds,
size : "lg"
});

Thanks.

**Comment by ktsadmin** [comment]
@aranderia with this latest update you can now call,

     jQuery("#hms_timer").countdowntimer("stop", "stop");
     jQuery("#hms_timer").countdowntimer("stop", "start");

to reset the timer. So in your case it would be:

    //set the timer originally.
    $('#hm_timer_'+t_id).countdowntimer({
      hours : hours,
      minutes : minutes,
      seconds : seconds,
      size : "lg"
    });

    //call to reset the timer
     jQuery("#hm_timer"+t_id).countdowntimer("stop", "stop");
     jQuery("#hm_timer"+t_id).countdowntimer("stop", "start");

This is the strategy I use now and I find it to be much cleaner. Be sure to initialize your timer separately, as the above selects an already initialized timer (if I remember correctly) then stops it and restarts it with your original parameters. Oh, and make sure you use **both** `stop` and `start` lines or it won't reset correctly. Hope this helps! Cheers!

**Comment by clveranis** [comment]
@aranderia with this latest update you can now call,

     jQuery("#hms_timer").countdowntimer("stop", "stop");
     jQuery("#hms_timer").countdowntimer("stop", "start");

to reset the timer. So in your case it would be:

    //set the timer originally.
    $('#hm_timer_'+t_id).countdowntimer({
      hours : hours,
      minutes : minutes,
      seconds : seconds,
      size : "lg"
    });

    //call to reset the timer
     jQuery("#hm_timer"+t_id).countdowntimer("stop", "stop");
     jQuery("#hm_timer"+t_id).countdowntimer("stop", "start");

This is the strategy I use now and I find it to be much cleaner. Be sure to initialize your timer separately, as the above selects an already initialized timer (if I remember correctly) then stops it and restarts it with your original parameters. Oh, and make sure you use **both** `stop` and `start` lines or it won't reset correctly. Hope this helps! Cheers!

**Comment by aranderia** [comment]
@clveranis Hey, thanks for the reply. I have tried the same thing.

```
//call to reset the timer 
$('#hm_timer_'+t_id).countdowntimer("stop", "stop"); 
$('#hm_timer_'+t_id).countdowntimer("stop", "start");
```

But now, I am facing this error. 

`Cannot read property 'type' of undefined`

This is the line where I am getting this error:

`stopTimer($(this), $(this).data('typefunc').type, $(this).data('opts').opts, $(this).data('typefunc').func);`

Any idea how to fix this?  Thanks.

@harshen
