### ISSUE TITLE
Reset Timer and Re-Initialize the Countdowntimer function

### ISSUE THREAD

**Issue by aranderia** [harshen/jquery-countdownTimer#29]
Can I reset the timer to my custom hours, minutes and seconds. Also, I have already initialized the timer once, how can I pass the new hours, minutes and seconds to the countdowntimer function.

**Comment by harshen** [comment]
Certainly, you can `destroy` the current instance and create the countdowntimer instance again with your new hours, minutes and seconds.

Visit the website for more information.

**Comment by aranderia** [comment]
@harshen It is still not working.. I destroy it and then reinitialize it using the same id, it increases the seconds interval by 1.

First I initialize it,

`$('#hm_timer_'+t_id).countdowntimer({
                                                    hours : hours,
                                                    minutes : minutes,
                                                    seconds : seconds,
                                                    size : "lg",
                                                    timeUp : timeIsUp,
                                                    beforeExpiryTime : "00:00:10:00",
                                                    beforeExpiryTimeFunction :  beforeExpiryFunc
                                                });`

Then, when I click on select box, I destroy the timer and calculate the new hours, minutes and seconds.

`$('#hm_timer_'+t_id).countdowntimer("destroy");`

Then, again reinitialize it.

`$('#hm_timer_'+t_id).countdowntimer({
                                                    hours : vm.hours,
                                                    minutes : vm.minutes,
                                                    seconds : vm.seconds,
                                                    size : "lg",
                                                    timeUp : timeIsUp,
                                                    beforeExpiryTime : "00:00:10:00",
                                                    beforeExpiryTimeFunction :  beforeExpiryFunc
                                                });`

Please let me know where I am making a mistake. Thanks.

**Comment by aranderia** [comment]
@harshen Please don't close the issue if hasn't got fixed.

**Comment by bhaumikb** [comment]
$('#hm_timer_'+t_id).countdowntimer("destroy");
will not work directly but you have to use "setTimeout" for 1 seconds (1000 ms) when you again $('#hm_timer_'+t_id).countdowntimer({ hours : vm.hours, minutes : vm.minutes, seconds : vm.seconds, size : "lg", timeUp : timeIsUp, beforeExpiryTime : "00:00:10:00", beforeExpiryTimeFunction : beforeExpiryFunc })

setTimeout(function(){
                                $('#hm_timer_'+t_id).countdowntimer({ hours : vm.hours, minutes : vm.minutes, seconds : vm.seconds, size : "lg", timeUp : timeIsUp, beforeExpiryTime : "00:00:10:00", beforeExpiryTimeFunction : beforeExpiryFunc })
                            }, 1000);
