### ISSUE TITLE
TimeIsUp Calling Although destroy countdowntimer

### ISSUE THREAD

**Issue by sagar-mi** [harshen/jquery-countdownTimer#30]
Hello,I have already destroyed countdowntimer but still it calling after several time.
It means for example i have only 2 minute left and i am destroying old instance and creating new one with 2:30 minutes but the code is in old timeup are running after 2 min.it should call 2nd time is up function instead of old function.

**Comment by harshen** [comment]
destroy function destroys current instance. Then reinitialize with new timer options. I don't think this is issue with timer. Check the website for more information.

**Comment by sagar-mi** [comment]
I already did same check here this is first instance and for that timeIsUp function is also there and for example timer going to end in 2 minutes but when i destroyed it , the code which is inside of timeisup functin should not be initialised if i have already destroyed instance but it still execute after 2 minute.

 ```
 $("#future_date" + iTime).countdowntimer({
                            startDate: moment(),
                            dateAndTime: new Date(moment.utc(newd, 'YYYY-MM-DD HH:mm:ss').local()),
                            size: "lg",
                            timeUp: timeIsUp
                        });

function timeIsUp() {
            swal('Auction has concluded. Thank you for participating.').then(function(){
                location.reload(true);
            })
        }
```
