### ISSUE TITLE
Won't count down in Safari

### ISSUE THREAD

**Issue by clveranis** [harshen/jquery-countdownTimer#32]
Just wanted to see if you are aware that this plugin doesn't seem to work in Safari. It will inject the HTML string into the specified element but it then just says '00:00:00'. 

Using the following code: 
  
    $('#timeCheck').countdowntimer({
        dateAndTime: "2018-05-08 19:55:01 UTC"
    });

Tested this plugin on two different websites that I've created, one using jQuery v1.11.2 and the other using jQuery v3.1.1, both sites work perfectly as expected when viewed with Google Chrome [v66.0.3359.139] while neither work using Safari [v10.1.1 (12603.2.4)]. I've also tried playing around editing the format of the date and time but no luck. 

I know that Safari is said to handle JS differently than Google Chrome but I don't know the specifics enough as to why Safari won't countdown the numbers as expected or what to do to fix it.

Would you please take a look and provide me with any suggestions as how I could get it working? I like this plugin and would rather not move to a different one but my sites need to support Safari unfortunately. Thanks in advance.

**Comment by zforsman** [comment]
I am noticing this same issue, did you ever find a fix?

**Comment by zforsman** [comment]
Hey @clveranis I noticed I had my dateAndTime formatted like yours, with dashes `2018-05-08`. The documentation calls for slashes `2018/05/08`, so I switched to that and it works just fine :)

**Comment by harshen** [comment]
Hi,

As suggested by @zforsman,
It doesn't seem to be an issue with the timer. For support please write me to harshenpandey@gmail.com.

Meanwhile You can also refer the documentation.
