### ISSUE TITLE
Pause Button don't work in multiple countDown

### ISSUE THREAD

**Issue by Darshit-Soni** [harshen/jquery-countdownTimer#33]
In one-page use three countdowns. But when I click on pause or stop button only one timer pause or stop other timer running. 

Here is my code : 

        `$("#totoaTime").countdowntimer({
            minutes : 4,
            seconds : 10,
            pauseButton : "pauseBtnhms",
            stopButton : "stopBtnhms"
        });`

        `$("#exerciseTime").countdowntimer({
            seconds : 30,
            pauseButton : "pauseBtnhms",
            stopButton : "stopBtnhms"
        });`

       `$("#exerciseTime1").countdowntimer({
            seconds : 30,
            pauseButton : "pauseBtnhms",
            stopButton : "stopBtnhms"
        });`

adding pause and stop button code only first timer is working.
How to work pause button in multiple countdownTimer?

**Comment by harshen** [comment]
Hi,

Try providing different pause/stop button id for different timers. 

It doesn't seem to be an issue with the timer. For support please write me to harshenpandey@gmail.com.

Meanwhile You can also refer the documentation.
