### ISSUE TITLE
timeUp callback is not working in IE7 and IE8

### ISSUE THREAD

**Issue by dhaval4neal** [harshen/jquery-countdownTimer#4]
Hi,
I have used the plugin in my application and it is working well in all browser other than IE 7 and IE 8.
In mentioned both browsers the timer works well but the "timeUp" callback is not working. Please let me know what should I do. A fragment of the code I have used is as shown below.

$("#timer").countdowntimer({
            minutes: 10,
            seconds: 0,
            timeUp: function () {
                alert("Your time is up");
            }
        });

**Comment by harshen** [comment]
Hi, 
Many websites are now dropping support for IE7, IE8 and IE9 as well.However, the plugin works well on IE9 and later versions.I don't feel a need to modify the code for it.
