### ISSUE TITLE
Stopping timer

### ISSUE THREAD

**Issue by sunil44** [harshen/jquery-countdownTimer#9]
Ho do I stop timer without passing button id?....or is it possible to provide two button's ID to stop callback??...Because i wanted to stop timer on one of the button click out of two

**Comment by harshen** [comment]
Timer can be stopped on click event. You have to provide id of the element on click of which you want the timer to stop.

**Comment by sunil44** [comment]
but if i want to stop timer on two buttons...so how do i provide two ids over there?........
